COMPONENT=NodeIfC
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION
CFLAGS += -DTASKLET_IS_TASK
CFLAGS += -I$(TOSDIR)/lib/printf

CFLAGS += -DCC2420_DEF_RFPOWER=31

include $(MAKERULES)

